version: '3.9'
services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      MIX_ENV: prod
      SECRET_KEY_BASE: yXW0ihG2Hxg3esEvWdfeBbfuMfMJxkup291vGnH4kY3GjYRNiI1u6NraKpSztDw7
